version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:alpine

  web:
    image: ${DOCKER_USERNAME}/equipment_project:v1.53
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - web

  bot:
    image: ${DOCKER_USERNAME}/equipment_project_bot:v1.14
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

volumes:
  static_value:
  media_value:
  postgres_data:
