version: '3.3'
services:

  db_test:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    env_file:
      - ./example.env

  web_test:
    image: guguruge/equipment_project:v0.8
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db_test
    env_file:
      - ./example.env

  nginx_test:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - web_test

volumes:
  static_value:
  media_value:
  postgres_data_test:
