from datetime import (
    date,
)

FIRST_ORGANIZATION_NAME = 'организация1'
SECOND_ORGANIZATION_NAME = 'организация2'
DOCUMENT_MANUAL_NAME = 'РЭ'
DOCUMENT_DESCRIPTION_NAME = 'ТО'
USER_NAME_STAFF = 'user_name_staff'
USER_NAME_NON_STAFF = 'user_name_non_staff'
DESTINATION_ADDRESS_FIRST = 'место_нахождения1'
DESTINATION_ADDRESS_SECOND = 'место_нахождения2'
INVENTORY_NUM_FIRST = 'инв1'
INVENTORY_NUM_SECOND = 'инв2'
EQUIPMENT_NAME_FIRST = 'наименование1'
EQUIPMENT_NAME_SECOND = 'наименование2'
EQUIPMENT_SERIAL_NUMBER_FIRST = 'тип1'
EQUIPMENT_SERIAL_NUMBER_SECOND = 'тип2'
EQUIPMENT_MODEL_FIRST = 'модель1'
EQUIPMENT_MODEL_SECOND = 'модель2'
MASS_EQUIPMENT_NAME = 'mass_equipment_name'
MASS_EQUIPMENT_SERIAL_NUMBER = 'mass_equipment_serial_number'
MASS_EQUIPMENT_MODEL = 'mass_equipment_model'
MASS_EQUIPMENT_MANUFACTURER = 'mass_equipment_manufacturer'
MASS_EQUIPMENT_NOMENCLATURE_KEY = 999
MASS_EQUIPMENT_DOCUMENT_PATH = 'mass_equipment_document_path'
MANUFACTURER_FIRST = 'производитель1'
MANUFACTURER_SECOND = 'производитель2'
NOMENCLATURE_KEY_FIRST = 111
NOMENCLATURE_KEY_SECOND = 222
DOCUMENT_PATH_FIRST = 'C://'
DOCUMENT_PATH_SECOND = 'C://dec//'
ATTESTATION_NAME_FIRST = 'аттестат1'
ATTESTATION_NAME_SECOND = 'аттестат2'
CALIBRATION_NAME_FIRST = 'калибровка1'
CALIBRATION_NAME_SECOND = 'калибровка2'
NEW_NAME = 'name'
DATE_JANUARY = date(2022, 1, 1)
DATE_FEBRUARY = date(2022, 2, 2)
DATE_MARCH = date(2022, 3, 3)
DATE_APRIL = date(2022, 4, 4)
DATE_MAY = date(2022, 5, 5)
DATE_JUNE = date(2022, 6, 6)
DATE_JULY = date(2022, 7, 7)
DATE_AUGUST = date(2022, 8, 8)
DATE_SEPTEMBER = date(2022, 9, 9)
